// Per-farm Pitti illustration URL resolver.
//
// Illustrations are generated by `pnpm tsx src/scripts/generate-pitti-batch.ts`
// (Runware FLUX-dev, Cassandre railway-poster style) and uploaded to Hetzner
// blob at `pitti-farm-images/<slug>/main.webp`. This resolver returns that URL
// for any farm slug; consumers render it with a graceful fallback (FarmCard ->
// FarmFallbackHero) when the asset is not yet generated (404). The Hetzner host
// is whitelisted in next.config.ts images.remotePatterns.
//
// Pitti = PLACE (council assignment): the branded hero for farms that have no
// real owner/admin photo. Real photos always win in FarmCard's hero priority.

const PITTI_BLOB_BASE =
  'https://farm-companion-blob-prod.hel1.your-objectstorage.com/pitti-farm-images'

/** The Hetzner blob URL for a farm's Pitti illustration. */
export function pittiFarmImageUrl(slug: string): string {
  return `${PITTI_BLOB_BASE}/${encodeURIComponent(slug)}/main.webp`
}
