// Apothecary — botanical-engraving sister style to Pitti
//
// Pitti is PLACE (atmospheric Cassandre railway-poster aesthetic).
// Apothecary is PRODUCT (intimate 18th-century botanical-plate aesthetic).
// They never appear together on the same hero; they share illustration
// honesty but contrast visual vocabulary, so the two together feel like
// a curated wardrobe rather than two sizes of one garment.
//
// References: Curtis's Botanical Magazine (1787-present), Hermès silk scarf
// botanical motifs, Aesop product packaging, Folio Society endpapers.
//
// Slice: 1.1.3a

/**
 * Apothecary visual signature prompt fragments.
 *
 * Negative prompt explicitly bans Pitti's geometric flat-color vocabulary
 * (Cassandre / Art Deco / vermilion / sea-ink) so the two styles stay
 * visually distinct even when generated by the same FLUX model.
 */
export const APOTHECARY_STYLE = {
  /** Universal style lead — every Apothecary artefact composes off this. */
  lead:
    'botanical engraving illustration, 18th century scientific plate style, ' +
    'sepia ink line work on cream parchment paper, ' +
    'detailed cross-hatching and stippling, hand-drawn precision, ' +
    'still life composition with classical balance, ornamental decorative border, ' +
    'subtle muted watercolor wash in olive and ochre tones, ' +
    'Curtis Botanical Magazine aesthetic, Hermes silk scarf quality, ' +
    'Folio Society endpaper detail, antique apothecary chart feel',

  /** Universal negative — bans photography AND Pitti's poster vocabulary. */
  negative:
    'photograph, photorealistic, 3d render, glossy, smooth gradient, ' +
    'modern digital illustration, vector clipart, ' +
    'text, watermark, signature, lettering, words, letters, characters, ' +
    'cartoon, anime, oversaturated, neon, pastel, fuzzy, soft, ' +
    // Anti-Pitti: keep the two styles from collapsing into each other
    'flat color blocks, geometric poster style, art deco, Cassandre style, ' +
    'vermilion red, sea-ink blue, two-color print, bold geometric composition',
} as const

/**
 * Build an Apothecary prompt by composing the universal style lead with a
 * subject phrase and any additional descriptive elements.
 */
export function buildApothecaryPrompt(
  subject: string,
  options: {
    additionalElements?: string[]
  } = {},
): string {
  const parts = [
    APOTHECARY_STYLE.lead,
    subject,
    ...(options.additionalElements || []),
  ].filter(Boolean)
  return parts.join(', ')
}

/**
 * Per-farm still-life illustration of what the shop sells.
 *
 * Used as the empty-state fallback on /shop/[slug] hero and FarmCard
 * thumbnails when no admin-uploaded real photo exists. Honest illustration
 * (clearly drawn, never pretending to be a real photo of the shop).
 */
export function buildApothecaryFarmOfferingsPrompt(
  offerings: string[] = ['seasonal produce'],
  county: string = 'rural England',
): string {
  const subjectsClause = offerings.slice(0, 3).join(', ')
  return buildApothecaryPrompt(
    `still life arrangement of ${subjectsClause} from ${county}`,
    {
      additionalElements: [
        'arranged on a flat surface with classical balance',
        'wide horizontal composition oriented for editorial header use',
        'natural specimens in season, no humans, no animals',
      ],
    },
  )
}

/**
 * Single-crop botanical specimen, taxonomic-plate style.
 * Used on seasonal produce pages and the SeasonalShowcase carousel.
 */
export function buildApothecarySeasonalPrompt(crop: string): string {
  return buildApothecaryPrompt(
    `single botanical specimen of ${crop}`,
    {
      additionalElements: [
        'centred specimen with root system or stem detail visible',
        'space below specimen for a taxonomic label (leave empty, no text)',
        'natural growth proportions, scientific accuracy',
      ],
    },
  )
}

/**
 * Small inline decorative accent — for editorial pull-quotes,
 * section dividers, FAQ icons, etc. Square aspect.
 */
export function buildApothecaryEditorialAccentPrompt(subject: string): string {
  return buildApothecaryPrompt(
    `small decorative botanical accent depicting ${subject}`,
    {
      additionalElements: [
        'minimal single-element composition',
        'square aspect, suitable for inline article decoration',
        'high contrast for use at small sizes',
      ],
    },
  )
}
